version: "3"
services:
  server:
    container_name: benchmark-server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      SERVER_CONTAINER_NAME: 'benchmark-server'

    networks:
          - bench

  client:
    container_name: client-app
    build:
      context: .
      dockerfile: Dockerfile.client

    depends_on:
      - server

    networks:
          - bench
    tty: true


networks:
    bench: {}
